server:
  port: 8002

#spring:
#  application:
#    name: consumer

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
#      defaultZone: http://localhost:7001/eureka/ #客户端注册进Eureka服务列表内
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/




