server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    registerWithEureka: false #表明自己是一个Eureka服务器
    fetchRegistry: false #表明自己是一个Eureka服务器
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

spring:
  application:
    name: eurake-server

